# Generated by Django 4.0.7 on 2022-08-17 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0030_delete_marginbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('free', models.DecimalField(decimal_places=12, max_digits=24)),
                ('used', models.DecimalField(decimal_places=12, max_digits=24)),
                ('total', models.DecimalField(decimal_places=12, max_digits=24)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='engine.trader')),
            ],
        ),
    ]
