# Generated by Django 4.0.6 on 2022-07-31 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('secret', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.CharField(max_length=255,
                 primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.CharField(max_length=255,
                 primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('timeout', models.IntegerField()),
                ('rate_limit', models.IntegerField()),
                ('symbol_separator', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=255,
                 primary_key=True, serialize=False)),
                ('client_order_id', models.CharField(max_length=255, null=True)),
                ('datetime', models.DateTimeField()),
                ('timestamp', models.BigIntegerField()),
                ('status', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('time_in_force', models.CharField(max_length=255)),
                ('side', models.CharField(max_length=255)),
                ('price', models.DecimalField(
                    decimal_places=12, max_digits=24, null=True)),
                ('average', models.DecimalField(
                    decimal_places=12, max_digits=24, null=True)),
                ('amount', models.DecimalField(decimal_places=12, max_digits=24)),
                ('filled', models.DecimalField(decimal_places=12, max_digits=24)),
                ('remaining', models.DecimalField(
                    decimal_places=12, max_digits=24)),
                ('cost', models.DecimalField(decimal_places=12, max_digits=24)),
                ('fee', models.DecimalField(decimal_places=12, max_digits=24)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('api_information', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='engine.apiinformation')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_begin', models.DateTimeField(auto_now_add=True)),
                ('date_time_end', models.DateTimeField(null=True)),
                ('state', models.CharField(max_length=255)),
                ('strategy', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='engine.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.CharField(max_length=255,
                 primary_key=True, serialize=False)),
                ('base', models.CharField(max_length=255)),
                ('quote', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(max_length=255, null=True)),
                ('telegram_username', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.CharField(max_length=255,
                 primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('timestamp', models.BigIntegerField()),
                ('symbol', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('side', models.CharField(max_length=255)),
                ('price', models.DecimalField(
                    decimal_places=12, max_digits=24, null=True)),
                ('taker_or_maker', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=12, max_digits=24)),
                ('cost', models.DecimalField(decimal_places=12, max_digits=24)),
                ('order', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='engine.order')),
                ('strategy', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='engine.strategy')),
                ('strategy_execution', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='engine.strategyexecution')),
                ('trader', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='engine.trader')),
            ],
        ),
        migrations.CreateModel(
            name='StrategySymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=255)),
                ('strategy', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='engine.strategy')),
                ('symbol', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='engine.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='StrategySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=12, max_digits=24)),
                ('comment', models.CharField(max_length=255)),
                ('strategy', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='engine.strategy')),
            ],
        ),
        migrations.AddField(
            model_name='strategy',
            name='strategy_class',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='engine.strategyclass'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='trader',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='engine.trader'),
        ),
        migrations.AddField(
            model_name='order',
            name='strategy',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='engine.strategy'),
        ),
        migrations.AddField(
            model_name='order',
            name='strategy_execution',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='engine.strategyexecution'),
        ),
        migrations.AddField(
            model_name='order',
            name='symbol',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='engine.symbol'),
        ),
        migrations.AddField(
            model_name='order',
            name='trader',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='engine.trader'),
        ),
        migrations.CreateModel(
            name='MarginBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('free', models.DecimalField(decimal_places=12, max_digits=24)),
                ('used', models.DecimalField(decimal_places=12, max_digits=24)),
                ('total', models.DecimalField(decimal_places=12, max_digits=24)),
                ('trader', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='engine.trader')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=12, max_digits=24)),
                ('datetime', models.DateTimeField()),
                ('daily_interest_rate', models.DecimalField(
                    decimal_places=12, max_digits=24)),
                ('status', models.CharField(max_length=255)),
                ('strategy', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='engine.strategy')),
                ('strategy_execution', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='engine.strategyexecution')),
                ('trader', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='engine.trader')),
            ],
        ),
        migrations.AddField(
            model_name='apiinformation',
            name='exchange',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='engine.exchange'),
        ),
        migrations.AddField(
            model_name='apiinformation',
            name='trader',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='engine.trader'),
        ),
    ]
