# Generated by Django 4.0.6 on 2022-08-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_rename_loan_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='id',
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False),
        ),
    ]
