# Generated by Django 4.0.6 on 2022-08-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_borrow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='base_min_size',
            field=models.DecimalField(
                decimal_places=12, default=1e-05, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbol',
            name='base_precision',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbol',
            name='market_order_min_fund',
            field=models.DecimalField(
                decimal_places=12, default=0.01, max_digits=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbol',
            name='market_order_precision_fund',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
