# Generated by Django 4.0.6 on 2022-08-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_symbol_base_min_size_symbol_base_precision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='position',
            field=models.CharField(default='short', max_length=255),
            preserve_default=False,
        ),
    ]
