# Generated by Django 4.0.6 on 2022-08-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_order_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategysymbol',
            old_name='side',
            new_name='position',
        ),
    ]
