# Generated by Django 4.0.6 on 2022-08-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_rename_side_strategysymbol_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='average_price_fee_included',
            field=models.DecimalField(
                decimal_places=12, max_digits=24, null=True),
        ),
    ]
