# Generated by Django 4.0.6 on 2022-08-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_order_average_price_fee_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_fee_adjusted',
            field=models.DecimalField(
                decimal_places=12, default=0, max_digits=24),
            preserve_default=False,
        ),
    ]
