# Generated by Django 4.0.6 on 2022-08-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_symbol_maker_fee_rate_symbol_taker_fee_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cost_fee_adjusted',
            new_name='cost_fee_adjusted',
        ),
    ]
