# Generated by Django 4.0.6 on 2022-08-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_rename_cost_minus_fee_order_cost_fee_adjusted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbol',
            old_name='base_min_size',
            new_name='base_min_amount',
        ),
    ]
