# Generated by Django 4.0.6 on 2022-08-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_rename_base_min_size_symbol_base_min_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_provide_fund_order',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
