# Generated by Django 4.0.6 on 2022-08-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_order_is_provide_fund_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_provide_fund_order',
            new_name='is_fund_provide_order',
        ),
    ]
