# Generated by Django 4.0.6 on 2022-08-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_rename_is_provide_fund_order_order_is_fund_provide_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyexecution',
            name='is_long_closed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategyexecution',
            name='is_short_closed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
