# Generated by Django 4.0.6 on 2022-08-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_strategyexecution_is_long_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyexecution',
            name='leverage',
            field=models.DecimalField(decimal_places=12, default=1, max_digits=24),
            preserve_default=False,
        ),
    ]
