# Generated by Django 4.0.6 on 2022-08-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_strategyexecution_last_long_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='interest',
            field=models.DecimalField(
                decimal_places=12, default=0.1, max_digits=24),
            preserve_default=False,
        ),
    ]
