# Generated by Django 4.0.6 on 2022-08-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_borrow_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='account_leverage',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
