# Generated by Django 4.0.6 on 2022-08-05 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_strategy_account_leverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='account_leverage',
        ),
    ]
