# Generated by Django 4.0.7 on 2022-08-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0020_strategy_last_strategy_execution_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='last_strategy_execution_id',
        ),
    ]
