# Generated by Django 4.0.7 on 2022-08-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0025_alter_strategy_last_strategy_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyexecution',
            name='is_long_success',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategyexecution',
            name='is_short_success',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
