# Generated by Django 4.0.7 on 2022-08-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0026_strategyexecution_is_long_success_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategyexecution',
            name='state',
        ),
    ]
