# Generated by Django 4.0.7 on 2022-08-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0027_remove_strategyexecution_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
