# Generated by Django 4.0.7 on 2022-08-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0028_delete_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='kline_open_1_min',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=24),
            preserve_default=False,
        ),
    ]
