# Generated by Django 4.0.7 on 2022-08-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0030_delete_marginbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyexecution',
            name='long_buy_cost',
            field=models.DecimalField(decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='strategyexecution',
            name='long_sell_cost',
            field=models.DecimalField(decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='strategyexecution',
            name='short_buy_cost',
            field=models.DecimalField(decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='strategyexecution',
            name='short_sell_cost',
            field=models.DecimalField(decimal_places=12, max_digits=24, null=True),
        ),
    ]
