# Generated by Django 4.0.7 on 2022-08-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0032_strategyexecution_is_strategy_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyexecution',
            name='date_time_begin',
            field=models.DateTimeField(null=True),
        ),
    ]
