# Generated by Django 4.0.7 on 2022-08-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0033_alter_strategyexecution_date_time_begin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyexecution',
            name='date_time_begin',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
