# Generated by Django 4.0.7 on 2022-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0034_alter_strategyexecution_date_time_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyexecution',
            name='strategy_execution_number_in_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
