# Generated by Django 4.0.7 on 2022-08-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0035_strategyexecution_strategy_execution_number_in_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysymbol',
            name='strategy_execution_number_in_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
