# Generated by Django 4.0.7 on 2022-08-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0036_strategysymbol_strategy_execution_number_in_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategyexecution',
            old_name='strategy_execution_number_in_day',
            new_name='number_in_day',
        ),
    ]
