# Generated by Django 4.0.7 on 2022-08-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0037_rename_strategy_execution_number_in_day_strategyexecution_number_in_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategyexecution',
            old_name='number_in_day',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='strategysymbol',
            old_name='strategy_execution_number_in_day',
            new_name='strategy_execution_task_id',
        ),
    ]
