# Generated by Django 4.0.7 on 2022-08-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0038_rename_number_in_day_strategyexecution_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyexecution',
            name='last_long_return_ratio',
            field=models.DecimalField(decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='strategyexecution',
            name='last_short_return_ratio',
            field=models.DecimalField(decimal_places=12, max_digits=24, null=True),
        ),
    ]
