# Generated by Django 4.0.7 on 2022-08-26 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_alter_crontabschedule_timezone'),
        ('engine', '0039_strategyexecution_last_long_return_ratio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyexecution',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
    ]
