# Generated by Django 4.0.7 on 2022-08-28 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0041_rename_task_id_strategyexecution_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyexecution',
            name='long_symbol',
            field=models.ForeignKey(default='BTC-USDT', on_delete=django.db.models.deletion.PROTECT, related_name='execution_long_symbol', to='engine.symbol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategyexecution',
            name='short_symbol',
            field=models.ForeignKey(default='BNB-USDT', on_delete=django.db.models.deletion.PROTECT, related_name='execution_short_symbol', to='engine.symbol'),
            preserve_default=False,
        ),
    ]
