# Generated by Django 4.0.7 on 2022-09-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0043_alter_strategyexecution_long_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSymbol',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('kucoin_symbol_choice', models.CharField(choices=[('E', 'Enable'), ('S', 'ShortOnly'), ('L', 'LongOnly'), ('D', 'Disable')], default='E', max_length=1)),
                ('binance_symbol_choice', models.CharField(choices=[('E', 'Enable'), ('S', 'ShortOnly'), ('L', 'LongOnly'), ('D', 'Disable')], default='E', max_length=1)),
            ],
        ),
    ]
